[package]
name = "azik-generator-web"
version = "0.1.1"
edition = "2021"

[dependencies]
axum = "0.8.1"
shuttle-axum = "0.51.0"
shuttle-runtime = "0.51.0"
tokio = "1.28.2"
generate_kana_table = "0.1.1"
